# Generated by Django 5.1.2 on 2024-10-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_laptop_seller_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('buyer', 'Acquirente'), ('seller', 'Fornitore')], max_length=20),
        ),
    ]
