# Generated by Django 5.1.2 on 2024-10-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='category',
            field=models.CharField(choices=[('', 'Select Category'), ('BL', 'Budget laptop'), ('HE', 'High end laptop'), ('CO', 'Convertible or 2-in-1'), ('GA', 'Gaming'), ('EN', 'Enterprise')], max_length=2),
        ),
    ]
