# Generated by Django 5.1.2 on 2024-10-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_laptop_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
