# Generated by Django 5.1.2 on 2024-10-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_sellerreview_laptopreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptopreview',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='sellerreview',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
