# Generated by Django 5.1.2 on 2024-10-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_alter_laptopreview_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptopreview',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sellerreview',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
